version: "3.8"

services:
    mongo:
        image: mongo:latest
        container_name: mongo_db
        restart: always
        ports:
            - "${MONGO_PORT}:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
