version: "3.8"

services:
    couchdb:
        image: couchdb:latest
        container_name: couchdb
        ports:
            - "5984:5984"
        volumes:
            - couchdb_data:/opt/couchdb/data
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

volumes:
    couchdb_data:
        driver: local
